### testing api call

### User
### Get User
GET  http://localhost:8000/


### Post new User
POST   http://localhost:8000/api/v1/users/
Content-Type: application/json

{
   "name":"test",
   "email":"b@b.com",
   "password":"abc"

}


### Post Login User
POST   http://localhost:8000/api/v1/users/login
Content-Type: application/json

{

   "email":"b@b.com",
   "password":"abc"

}

### GET user Profile
GET   http://localhost:8000/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3NDI0NjAzNzcsImV4cCI6MTc0MjU0Njc3N30.ZhIyKL3iDadhsSG-NxmSvxngq1Y3KALemuWxJfVd85E